steps:
  # Install frontend dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'

  # Build frontend with production API URL
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'REACT_APP_API_URL=https://zammer2.uc.r.appspot.com/api'

  # Copy frontend build to backend
  - name: 'ubuntu'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        mkdir -p backend/public
        cp -r frontend/build/* backend/public/

  # Install backend dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--production']
    dir: 'backend'

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', 'app.yaml', '--promote', '--quiet']

timeout: '1600s'