"""
Seed Banner URLs to MongoDB
Reads banner_urls.json (generated by generate_and_upload_banners.py)
and inserts banner documents into the MongoDB Banner collection.

Usage:
    python seed_banners_to_db.py [MONGO_URI]

    If MONGO_URI is not provided, it will try to read from backend/.env
"""

import os
import sys
import json
from pathlib import Path
from datetime import datetime

# MongoDB connection
from pymongo import MongoClient
from dotenv import load_dotenv

# Load environment
BACKEND_ENV = Path(__file__).parent.parent / "backend" / ".env"
if BACKEND_ENV.exists():
    load_dotenv(BACKEND_ENV)

BANNER_URLS_FILE = Path(__file__).parent / "banner_urls.json"
TLS_CERT_FILE = Path(__file__).parent.parent / "backend" / "rds-combined-ca-bundle.pem"

def main():
    print("=" * 60)
    print("ZAMMER Banner Database Seeder")
    print("=" * 60)

    # Check if banner_urls.json exists
    if not BANNER_URLS_FILE.exists():
        print(f"[ERROR] {BANNER_URLS_FILE} not found!")
        print("Please run generate_and_upload_banners.py first.")
        sys.exit(1)

    # Load banner URLs
    with open(BANNER_URLS_FILE, "r") as f:
        banner_data = json.load(f)

    print(f"\n[OK] Loaded banner URLs:")
    print(f"  Level 1: {len(banner_data.get('level1', []))} banners")
    print(f"  Level 2: {len(banner_data.get('level2', []))} banners")
    print(f"  Level 3: {len(banner_data.get('level3', []))} banners")

    # Connect to MongoDB
    mongo_uri = sys.argv[1] if len(sys.argv) > 1 else os.getenv("MONGO_URI")

    if not mongo_uri:
        print("[ERROR] MONGO_URI not provided!")
        print("Usage: python seed_banners_to_db.py [MONGO_URI]")
        print("Or set MONGO_URI in backend/.env file")
        sys.exit(1)

    try:
        # MongoDB connection options (matching your backend config)
        connection_options = {
            "tls": True,
            "tlsAllowInvalidCertificates": False,
            "serverSelectionTimeoutMS": 15000,
            "connectTimeoutMS": 15000,
        }

        # Add TLS certificate if it exists
        if TLS_CERT_FILE.exists():
            connection_options["tlsCAFile"] = str(TLS_CERT_FILE)
            print(f"[INFO] Using TLS certificate: {TLS_CERT_FILE.name}")

        print(f"[INFO] Connecting to MongoDB...")
        client = MongoClient(mongo_uri, **connection_options)

        # Test connection
        client.admin.command('ping')

        db = client.get_default_database()
        banners_collection = db["banners"]
        print(f"[OK] Connected to MongoDB database: {db.name}")
    except Exception as e:
        print(f"[ERROR] Failed to connect to MongoDB: {e}")
        print("\nTroubleshooting:")
        print("1. Check if MongoDB server is running")
        print("2. Verify MONGO_URI is correct")
        print("3. Check network connectivity")
        print("4. Verify TLS certificate path")
        sys.exit(1)

    # Clear existing banners (optional - comment out if you want to keep existing)
    print("\n[INFO] Clearing existing banners...")
    delete_result = banners_collection.delete_many({})
    print(f"  Deleted {delete_result.deleted_count} existing banner(s)")

    # Prepare banner documents
    banner_documents = []

    # Level 1 banners
    for idx, banner in enumerate(banner_data.get("level1", []), start=1):
        doc = {
            "level": 1,
            "categoryLevel1": banner["categoryLevel1"],
            "categoryLevel2": None,
            "categoryLevel3": None,
            "imageUrl": banner["imageUrl"],
            "cloudinaryPublicId": banner["cloudinaryPublicId"],
            "title": banner["categoryLevel1"],
            "subtitle": f"Explore {banner['categoryLevel1']} collection",
            "isActive": True,
            "displayOrder": idx,
            "createdAt": datetime.utcnow(),
            "updatedAt": datetime.utcnow(),
        }
        banner_documents.append(doc)

    # Level 2 banners
    for idx, banner in enumerate(banner_data.get("level2", []), start=1):
        doc = {
            "level": 2,
            "categoryLevel1": banner["categoryLevel1"],
            "categoryLevel2": banner["categoryLevel2"],
            "categoryLevel3": None,
            "imageUrl": banner["imageUrl"],
            "cloudinaryPublicId": banner["cloudinaryPublicId"],
            "title": banner["categoryLevel2"],
            "subtitle": f"Discover {banner['categoryLevel2']}",
            "isActive": True,
            "displayOrder": idx,
            "createdAt": datetime.utcnow(),
            "updatedAt": datetime.utcnow(),
        }
        banner_documents.append(doc)

    # Level 3 banners
    for idx, banner in enumerate(banner_data.get("level3", []), start=1):
        doc = {
            "level": 3,
            "categoryLevel1": banner["categoryLevel1"],
            "categoryLevel2": banner["categoryLevel2"],
            "categoryLevel3": banner["categoryLevel3"],
            "imageUrl": banner["imageUrl"],
            "cloudinaryPublicId": banner["cloudinaryPublicId"],
            "title": banner["categoryLevel3"],
            "subtitle": f"Shop {banner['categoryLevel3']}",
            "isActive": True,
            "displayOrder": idx,
            "createdAt": datetime.utcnow(),
            "updatedAt": datetime.utcnow(),
        }
        banner_documents.append(doc)

    # Insert into MongoDB
    if banner_documents:
        print(f"\n[INFO] Inserting {len(banner_documents)} banner documents...")
        insert_result = banners_collection.insert_many(banner_documents)
        print(f"[OK] Inserted {len(insert_result.inserted_ids)} banners successfully!")
    else:
        print("[WARN] No banner documents to insert")

    # Verify insertion
    count_l1 = banners_collection.count_documents({"level": 1, "isActive": True})
    count_l2 = banners_collection.count_documents({"level": 2, "isActive": True})
    count_l3 = banners_collection.count_documents({"level": 3, "isActive": True})

    print("\n[VERIFY] Banner counts in database:")
    print(f"  Level 1: {count_l1}")
    print(f"  Level 2: {count_l2}")
    print(f"  Level 3: {count_l3}")

    print("\n" + "=" * 60)
    print("Database seeding complete!")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Start your backend server: cd backend && npm start")
    print("2. Visit http://localhost:3000/user/dashboard to see the banners")


if __name__ == "__main__":
    main()
